# Project: Project2
# Makefile created by Dev-C++ 5.6.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"E:/PENDRIVE/FATEC/Algoritmos/Dev-Cpp 5.6.2 TDM-GCC x64 4.8.1 Portable/Dev-Cpp/MinGW64/lib" -L"E:/PENDRIVE/FATEC/Algoritmos/Dev-Cpp 5.6.2 TDM-GCC x64 4.8.1 Portable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/PENDRIVE/FATEC/Algoritmos/Dev-Cpp 5.6.2 TDM-GCC x64 4.8.1 Portable/Dev-Cpp/MinGW64/include" -I"E:/PENDRIVE/FATEC/Algoritmos/Dev-Cpp 5.6.2 TDM-GCC x64 4.8.1 Portable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/PENDRIVE/FATEC/Algoritmos/Dev-Cpp 5.6.2 TDM-GCC x64 4.8.1 Portable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"E:/PENDRIVE/FATEC/Algoritmos/Dev-Cpp 5.6.2 TDM-GCC x64 4.8.1 Portable/Dev-Cpp/MinGW64/include" -I"E:/PENDRIVE/FATEC/Algoritmos/Dev-Cpp 5.6.2 TDM-GCC x64 4.8.1 Portable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/PENDRIVE/FATEC/Algoritmos/Dev-Cpp 5.6.2 TDM-GCC x64 4.8.1 Portable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"E:/PENDRIVE/FATEC/Algoritmos/Dev-Cpp 5.6.2 TDM-GCC x64 4.8.1 Portable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = Project2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
